# Find atleast 10 math module methods (other than the examples shown) and write
# code to show their utility. Also explain the functions.
import math

def main():
    print("===============================================================")
    print("1. 'math.fabs(x)' to find abosolute value of x")
    i=int(input("Enter an integer input: "))
    print("The abosolute value of ",i,":", math.fabs(i))
    print("===============================================================")
    print("2. 'math.sqrt(n)' return square root of the nonnegative integer n")
    i=int(input("Enter an non-negative integer input: "))
    print("The square root of ",i,":", math.sqrt(i))
    print("===============================================================")
    print("3. 'math.pow(x, y)' return x raised to the power y")
    b=int(input("Enter the base value: "))
    p=int(input("Enter the power value: "))
    print("The value of '",b,"^",p,"' =", math.pow(b,p))
    print("===============================================================")
    print("4. 'math.degrees(x)' convert angle x from radians to degrees")
    r=float(input("Enter the angle in radians: "))
    print("The degree value of ",r,":", math.degrees(r))
    print("===============================================================")
    print("5. 'math.radians(x)' convert angle x from degrees to radians")
    d=float(input("Enter the angle in degree: "))
    print("The radians value of ",d,":", math.radians(d))
    print("===============================================================")
    print("6. 'math.comb(n, k)' evaluates to n! / (k! * (n - k)!) when k <= n and evaluates to zero when k > n")
    n=int(input("Enter the value of total itemset: "))
    k=int(input("Enter the value of selected itemset: "))
    print("The combination value is :", math.comb(n,k))
    print("===============================================================")
    print("7. 'math.copysign(x, y)' return a float with the magnitude (absolute value) of x but the sign of y")
    x=float(input("Enter the value of x: "))
    y=float(input("Enter the value of y: "))
    print("The output is :", math.copysign(x, y))
    print("===============================================================")
    print("8. 'math.perm(n, k)' evaluates to n! / (n - k)! when k <= n and evaluates to zero when k > n")
    n=int(input("Enter the value of total itemset: "))
    k=int(input("Enter the value of selected itemset: "))
    print("The combination value is :", math.perm(n,k))
    print("===============================================================")
    print("9. 'math.remainder(x, y)' return remainder after x/y")
    x=int(input("Enter the value of x: "))
    y=int(input("Enter the value of y: "))
    print("The remainder value is :", math.remainder(x,y))
    print("===============================================================")
    print("10. 'math.log10(x)' return the base-10 logarithm of x. This is usually more accurate than log(x, 10)")
    x=int(input("Enter the value of x: "))
    print("The output value is :", math.log10(x))
    
main()
